FROM nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y make python3-pip
RUN pip install poetry
RUN mkdir -p /work
COPY . /work

WORKDIR /work
RUN poetry config virtualenvs.in-project true --local
RUN poetry install --no-interaction --no-root

RUN apt update && apt install software-properties-common python3-launchpadlib -y
RUN add-apt-repository ppa:sumo/stable
RUN apt install sumo sumo-tools -y

ENV PATH="/work/.venv/bin:$PATH"
