general:
  log_level: DEBUG
  data_scripts:
    path: data

data:
  scenarios_path: src/core/data
  temp_path: src/core/data/nets
  source_path: src/core/data/scenarios
  scenarios: [2way-single-intersection, single-intersection, 2x2grid, 3x3grid, 4x4loop]

train:
  script_path: src/training/train.py
  model_path: src/core/saved_models
  model_name: model
  model_file: model.pth
  dir_reports:
  device_id: 0
  scenario: 2way-single-intersection
  environment:
    net_file: single-intersection.net.xml
    route_file: single-intersection-vhvh.rou.xml
    agent_result: src/training/results
    single_agent: True
    gui: False
    num_steps: 10000
  hyper:
    epsilon_start: 1.0
    epsilon_final: 0.01
    epsilon_decay: 30000
    gamma: 0.99
    lr: 1e-4
    target_update_freq: 1000
    exp_replay_size: 100000
    batch_size: 32
    alpha: 0.6
    beta: 0.4
    beta_raise: 100000
    beta_stop: 1
    learn_start: int(1e3)
    steps: int(1e4)
    use_lr_decay: False
    use_soft_update: False
    grad_clip: False

deploy:
  script_path: src/training/train.py
  model_path: src/core/saved_models
  model_file: model.pth
  evaluate_times: 10
  verbose: True
  device_id: 0
  scenario: 2way-single-intersection
  environment:
    net_file: single-intersection.net.xml
    route_file: single-intersection-vhvh.rou.xml
    agent_result: src/training/results
    single_agent: True
    gui: False
    num_steps: 10000

compose:
  script_path: compose_train.yaml

metrics:
  raw_metrics_path: reward.csv

plots:
  plot_path: 'reward.png'

