name: Tests

on:
  push:
    branches: ["main", "feature_*"]
  pull_request:
    branches: ["main"]

env:
  SOURCE_FILES_PATH: src/training

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Poetry
        run: |
          pip install poetry          
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          # last version is default
          python-version: |
            ${{ matrix.python_version }}            
          cache: poetry
      - name: Cache Pre-Commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: pre-commit-
      - name: Install Python Dependencies
        run: poetry install --sync
      - name: Run Pre-Commit Checks
        run: poetry run pre-commit run $SOURCE_FILES_PATH --color=always --show-diff-on-failure
      - name: Run Tests
        run: poetry run pytest -v